# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    # branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  # old-school build and jar method. No tests run or compiled.
  build-1_6: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build for java 1.6, however don't run any tests
        java: [ 1.6 ]
    name: Java ${{ matrix.java }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Setup java
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: ${{ matrix.java }}
      - name: Compile Java ${{ matrix.java }}
        run: |
          mkdir -p target/classes
          javac -d target/classes/ src/main/java/org/json/*.java
      - name: Create java ${{ matrix.java }} JAR
        run: |
          jar cvf target/org.json.jar -C target/classes .
      - name: Upload Java ${{ matrix.java }} JAR
        uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # v1.0.0
        with:
          name: Java ${{ matrix.java }} JAR
          path: target/org.json.jar
      
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build against supported Java LTS versions:
        java: [ 8, 11 ]
    name: Java ${{ matrix.java }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Setup java
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: ${{ matrix.java }}
      - name: Compile Java ${{ matrix.java }}
        run: mvn clean compile -Dmaven.compiler.source=${{ matrix.java }} -Dmaven.compiler.target=${{ matrix.java }} -Dmaven.test.skip=true -Dmaven.site.skip=true -Dmaven.javadoc.skip=true
      - name: Run Tests ${{ matrix.java }}
        run: |
          mvn test -Dmaven.compiler.source=${{ matrix.java }} -Dmaven.compiler.target=${{ matrix.java }}
      - name: Build Test Report ${{ matrix.java }}
        if: ${{ always() }}
        run: |
          mvn surefire-report:report-only -Dmaven.compiler.source=${{ matrix.java }} -Dmaven.compiler.target=${{ matrix.java }}
          mvn site -DgenerateReports=false -Dmaven.compiler.source=${{ matrix.java }} -Dmaven.compiler.target=${{ matrix.java }}
      - name: Upload Test Results ${{ matrix.java }}
        if: ${{ always() }}
        uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # v1.0.0
        with:
          name: Test Results ${{ matrix.java }}
          path: target/surefire-reports/
      - name: Upload Test Report ${{ matrix.java }}
        if: ${{ always() }}
        uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # v1.0.0
        with:
          name: Test Report ${{ matrix.java }}
          path: target/site/
